conditioning:
  method: mpgd # Do not touch
  params:
    scale: 1.0

# data:
#   name: ffhq
#   root: ./data/samples/
data:
  name: celeba
  root: ./data/celeba/
measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  noise: 
    name: gaussian
    noise_scale: 0.01

